name: 'Deploy to AWS S3'
description: 'Deploy to static website via AWS S3'
inputs:
  bucket:
    description: 'The S3 bucket name.'
    required: true
  bucket-region:
    description: 'The S3 bucket region.'
    required: false
    default: 'ap-southeast-1'
  dist-folder:
    description: 'The folder containing the static website files.'
    required: true
runs:
  using: 'node16'
  main: 'main.js'
